movie:
  required:
    movieFile:
      type: i/video
      choice: first size
  optional:
    cover:
      type: i/image
      choice: filename like movieFile
    nfo:
      type: i/nfo
      choice: filename like movieFile
    images:
      type: s/imageSet
      max: 0
      weight: 0
  terminal: True