seriesSeason:
  required:
    episodes:
      type: i/video
      max: 0
  optional:
    subtitles:
      type: i/subtitle
      max: 0
      choice: filename like episodes
    cover:
      type: i/image
      max: 0
      weight: 0