variousMovies:
  required:
    movies:
      type: i/video
      max: 0
  optional:
    others:
      type: s/variousMovies
      max: 0
    movieDirs:
      type: s/movie
      max: 0
  terminal: False